clean up
ISOC-Research/py3-rpki-utils pull request #1
Opened 2022-06-23 03:53 UTC by aftabsiddiqui

renamed folder and cleaned up readme.md

2022-06-23 03:58 UTC, ppaeps requested changes
This looks good in principle.  I would not recommend escalating privileges unnecessarily in the documentation.  If it doesn't work without privilege, we should fix that bug instead of working around it.

2022-06-23 03:58 UTC, ppaeps commented on README.md
> +$ cd print
Any particular reasons for the `sudo`?  This should not require privilege.

2022-06-23 04:22 UTC, aftabsiddiqui commented on README.md
> +$ cd print
oh thats privilege issue was on my local system, I over looked that. No need for sudo for any of these operations.

2022-06-23 04:23 UTC, ppaeps approved these changes

2022-06-23 04:36 UTC, ppaeps commented
I've merged these changes into main after rewriting history a bit.  Thanks for the patch!

2022-06-29 02:04 UTC, ppaeps commented
This was rebased and merged as 7addd817c3492e87c3f0d654ff0470aa0627671b.  GitHub isn't smart enough to notice and auto-close this PR.

2022-06-29 02:04 UTC, closed without merging